# -*- coding: utf-8 -*-
"""Buenaventura-Espanol FA3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mhXM0pJhNopPOqTgPyOftYCKZJjBq_h
"""

import numpy as np
import pandas as pd
from scipy import stats

# Test scores
scores = np.array([
    88,45,53,86,33,86,85,30,89,53,41,96,56,38,62,
    71,51,86,68,29,28,47,33,37,25,36,33,94,73,46,
    42,34,79,72,88,99,82,62,57,42,28,55,67,62,60,
    96,61,57,75,93,34,75,53,32,28,73,51,69,91,35
])

# Descriptive statistics
data = {
    "Valid": len(scores),
    "Mode": stats.mode(scores, keepdims=True).mode[0],
    "Median": np.median(scores),
    "Mean": np.mean(scores),
    "Std. Deviation": np.std(scores, ddof=1),
    "Variance": np.var(scores, ddof=1),
    "Skewness": stats.skew(scores),
    "Std. Error of Skewness": np.sqrt(6 / len(scores)),
    "Kurtosis": stats.kurtosis(scores),
    "Std. Error of Kurtosis": np.sqrt(24 / len(scores)),
    "Minimum": np.min(scores),
    "Maximum": np.max(scores),
    "25th Percentile (Q1)": np.percentile(scores, 25),
    "50th Percentile (Q2)": np.percentile(scores, 50),
    "75th Percentile (Q3)": np.percentile(scores, 75),
    "90th Percentile (D9)": np.percentile(scores, 90),
    "95th Percentile (P95)": np.percentile(scores, 95)
}

# Create table
df = pd.DataFrame.from_dict(data, orient="index", columns=["Score"])
df = df.round(3)

print(df)